# Generated by Django 3.1.6 on 2021-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
