# Generated by Django 3.1.6 on 2021-07-10 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0004_auto_20210710_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.date.today, unique_for_date='creator'),
        ),
    ]
