# Generated by Django 3.1.6 on 2021-07-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0005_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
