# Generated by Django 3.1.6 on 2021-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0006_auto_20210710_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='negatives',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mood',
            name='positives',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mood',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
